# Generated by Django 4.0.6 on 2022-07-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0003_tasklabelrelation_task_labels_tasklabelrelation_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(through='tasks.TaskLabelRelation', to='labels.label', verbose_name='Метки'),
        ),
    ]
