# Generated by Django 4.0.6 on 2022-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
