# Generated by Django 4.0.6 on 2022-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_taskstatus_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
